### ISSUE TITLE
schema plugins submodule problems

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/core-geonetwork#1]
I get the following error message when using git to update my copy of the repo:
Fetched in submodule path 'schemaPlugins', but it did not contain eda1fd1f93983fbdf7dd612cb7b23204a55ea043. Direct fetching of that commit failed.

https://github.com/smart-facility/core-geonetwork/blob/2.10.x/.gitmodules#L20 refers to a branch of schema-plugins that doesn't exist on github, so I'm wondering if you've missed pushing something in the submodule?

**Comment by mcpgovernance** [comment]
Hi matthew - doesn't look like it but will check it shortly. Cheers, Simon

On Mon, Nov 28, 2016 at 12:11 PM, Matthew Berryman <notifications@github.com

**Comment by sppigot** [comment]
Hi Matthew,


At some stage this submodule seems to have begun tracking a branch (2.10.x) that doesn't exist in your fork - interesting. In any case it should be ok now - needs to track master so to get things on an even keel again try this from the directory containing your working copy:


git submodule update --init


I have been pushing updates to your branch for some time - however I'll check that all is still ok with your fork shortly - it ought to be, but best check.


Cheers, Simon


________________________________

**Comment by matthewberryman** [comment]
Yeah it all looks good now, thanks.

**Comment by sppigot** [comment]
Great - built the installed and checked the editor - there was a comma missing from one of the .js files - fixed and editor works fine. So looks good.
